project_id = "bkrxxvnjivvzwslvvwun"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "auth", "realtime"]
max_rows = 1000

[db]
port = 54322

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327

[auth]
enabled = true
port = 54328

[edge_functions]
enabled = true
port = 54329

[functions.process-locations-csv]
verify_jwt = false

[functions.process-assets-csv]
verify_jwt = false

[functions.custom-oauth-exchange]
verify_jwt = false

[functions.secure-file-processor]
verify_jwt = true

[functions.process-regions-csv]
verify_jwt = false