"""Asset location hist

Revision ID: 2feaf10b4702
Revises: f711b4bc74db
Create Date: 2025-08-20 14:50:15.204893

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2feaf10b4702'
down_revision: Union[str, Sequence[str], None] = 'f711b4bc74db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset_location_updates',
    sa.Column('id', sa.String(length=36), server_default=sa.text('uuid()'), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('old_location_id', sa.String(length=36), nullable=False),
    sa.Column('new_location_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['new_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['old_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'asset_transfer_items', 'locations', ['destination_location_id'], ['id'])
    op.alter_column('workflow_steps', 'scope',
               existing_type=mysql.VARCHAR(length=64),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('workflow_steps', 'scope',
               existing_type=mysql.VARCHAR(length=64),
               nullable=True)
    op.drop_constraint(None, 'asset_transfer_items', type_='foreignkey')
    op.drop_table('asset_location_updates')
    # ### end Alembic commands ###
