"""Next changes

Revision ID: 36dd9d229b30
Revises: 2abb8c21f071
Create Date: 2025-08-08 14:49:53.795887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36dd9d229b30'
down_revision: Union[str, Sequence[str], None] = '2abb8c21f071'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country_recommendator_assignments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('country_id', sa.String(length=36), nullable=False),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user_roles.user_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'category_id', name='ux_country_category_recommendator')
    )
    op.create_index(op.f('ix_country_recommendator_assignments_category_id'), 'country_recommendator_assignments', ['category_id'], unique=False)
    op.create_index(op.f('ix_country_recommendator_assignments_country_id'), 'country_recommendator_assignments', ['country_id'], unique=False)
    op.add_column('branches', sa.Column('branch_manager_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_branches_branch_manager_id'), 'branches', ['branch_manager_id'], unique=False)
    op.create_foreign_key(None, 'branches', 'user_roles', ['branch_manager_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'branches', type_='foreignkey')
    op.drop_index(op.f('ix_branches_branch_manager_id'), table_name='branches')
    op.drop_column('branches', 'branch_manager_id')
    op.drop_index(op.f('ix_country_recommendator_assignments_country_id'), table_name='country_recommendator_assignments')
    op.drop_index(op.f('ix_country_recommendator_assignments_category_id'), table_name='country_recommendator_assignments')
    op.drop_table('country_recommendator_assignments')
    # ### end Alembic commands ###
