"""Workflow tables

Revision ID: 3ee11b6ae969
Revises: 91a5c787ac31
Create Date: 2025-08-11 13:02:46.204859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ee11b6ae969'
down_revision: Union[str, Sequence[str], None] = '91a5c787ac31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_instances',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scenario_name', sa.String(length=128), nullable=False),
    sa.Column('business_ref', sa.String(length=128), nullable=False),
    sa.Column('requester_email', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('current_step', sa.Integer(), nullable=True),
    sa.Column('callback_url', sa.String(length=255), nullable=True),
    sa.Column('callback_token', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_instances_business_ref'), 'workflow_instances', ['business_ref'], unique=False)
    op.create_table('workflow_scenarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('rules', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('workflow_steps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('actor_type', sa.String(length=64), nullable=False),
    sa.Column('assigned_actor_ids', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workflow_steps')
    op.drop_table('workflow_scenarios')
    op.drop_index(op.f('ix_workflow_instances_business_ref'), table_name='workflow_instances')
    op.drop_table('workflow_instances')
    # ### end Alembic commands ###
