"""Workflow tables

Revision ID: 986ecf150c67
Revises: 3ee11b6ae969
Create Date: 2025-08-13 12:20:37.087988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '986ecf150c67'
down_revision: Union[str, Sequence[str], None] = '3ee11b6ae969'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('asset_transfers', sa.Column('source_branch_id', sa.String(length=36), nullable=True))
    op.add_column('asset_transfers', sa.Column('destination_branch_id', sa.String(length=36), nullable=True))
    op.add_column('asset_transfers', sa.Column('remarks', sa.String(length=1024), nullable=True))
    op.alter_column('asset_transfers', 'source_location_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.alter_column('asset_transfers', 'destination_location_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=True)
    op.create_foreign_key(None, 'asset_transfers', 'branches', ['destination_branch_id'], ['id'])
    op.create_foreign_key(None, 'asset_transfers', 'branches', ['source_branch_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'asset_transfers', type_='foreignkey')
    op.drop_constraint(None, 'asset_transfers', type_='foreignkey')
    op.alter_column('asset_transfers', 'destination_location_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.alter_column('asset_transfers', 'source_location_id',
               existing_type=mysql.VARCHAR(length=36),
               nullable=False)
    op.drop_column('asset_transfers', 'remarks')
    op.drop_column('asset_transfers', 'destination_branch_id')
    op.drop_column('asset_transfers', 'source_branch_id')
    # ### end Alembic commands ###
