"""Update tables

Revision ID: ae6068934f89
Revises: 7a46b2dfee00
Create Date: 2025-07-31 08:58:24.510184

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae6068934f89'
down_revision: Union[str, Sequence[str], None] = '7a46b2dfee00'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('erp_sync_configs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sync_type', sa.String(length=32), nullable=False),
    sa.Column('last_sync_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sync_type', name='uq_sync_type')
    )
    op.create_table('asset_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_number', sa.String(length=64), nullable=False),
    sa.Column('source_location_id', sa.String(length=36), nullable=False),
    sa.Column('destination_location_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['destination_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transfer_number')
    )
    op.create_table('asset_transfer_approvals',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('approver_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['approver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['asset_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_transfer_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_id', sa.String(length=36), nullable=False),
    sa.Column('asset_id', sa.String(length=36), nullable=False),
    sa.Column('barcode', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['transfer_id'], ['asset_transfers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('asset_transfer_items')
    op.drop_table('asset_transfer_approvals')
    op.drop_table('asset_transfers')
    op.drop_table('erp_sync_configs')
    # ### end Alembic commands ###
