"""Workflow Inbox

Revision ID: f711b4bc74db
Revises: 2cc9e1843214
Create Date: 2025-08-14 13:11:45.316012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f711b4bc74db'
down_revision: Union[str, Sequence[str], None] = '2cc9e1843214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_inbox',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('instance_id', sa.String(length=36), nullable=False),
    sa.Column('step_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('delivered_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['workflow_instances.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_inbox_instance_id'), 'workflow_inbox', ['instance_id'], unique=False)
    op.create_index(op.f('ix_workflow_inbox_user_id'), 'workflow_inbox', ['user_id'], unique=False)
    op.add_column('workflow_steps', sa.Column('is_current', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workflow_steps', 'is_current')
    op.drop_index(op.f('ix_workflow_inbox_user_id'), table_name='workflow_inbox')
    op.drop_index(op.f('ix_workflow_inbox_instance_id'), table_name='workflow_inbox')
    op.drop_table('workflow_inbox')
    # ### end Alembic commands ###
